### ISSUE TITLE
Can't tile TIFF files

### ISSUE THREAD

**Issue by Liao-MH** [slideflow/slideflow#437]
## Description
Dear any,
I am a fresh rookie in digital pathology and trying to tile my TIFF slides (5000x5000). But after creating a project, I can't tile the slides and there is an "EOFError".

## To Reproduce
1. code:
```Pyhton
# setting a project

P = sf.create_project(
    name = "HCC_IHC",
    root='/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/project',
    slides='/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/project/slide_and_tile/slide',
    tfrecords="/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/project/slide_and_tile/tiles"
)
# %%
print(P)
# %%
#P = sf.load_project('/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/project')

# %%
# Extract tiles at 256 pixels, 0.5 um/px
#P.extract_tiles(tile_px=256, tile_um=128)
P.extract_tiles(tile_px=256, 
                tile_um=128,
                whitespace_fraction=0.5  # discard tiles with this fraction of whitespace
                )
```
2. Error1:
```
[10:08:57] INFO     Column 'slide' missing in annotations.                                                         
           INFO     Attempting to associate patients with slides...                                                
           INFO     Done; associated slides with 36 annotations.                                                   
           INFO     Slide reading backend: libvips                                                                 
           INFO     Filtering tiles by whitespace fraction                                                         
           INFO     Filtering tiles by grayspace fraction                                                          
           INFO     Working on dataset source HCC_IHC...                                                           
           INFO     Extracting tiles from 36 slides (tile_px=256, tile_um=128)                                     
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/lmh/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/lmh/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/lmh/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/lmh/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/lmh/miniconda3/envs/slideflow/lib/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/lmh/miniconda3/envs/slideflow/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/lmh/miniconda3/envs/slideflow/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/slideflow_try.py", line 11, in <module>
    P = sf.create_project(
  File "/Users/lmh/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py", line 3813, in create
    raise OSError(f"A project already exists at {root}")
OSError: A project already exists at [/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/project](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/project)
```
3. Error2:
```
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
File /Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/slideflow_try.py:4
      [1](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/slideflow_try.py:1) # %%
      [2](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/slideflow_try.py:2) # Extract tiles at 256 pixels, 0.5 um/px
      [3](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/slideflow_try.py:3) #P.extract_tiles(tile_px=256, tile_um=128)
----> [4](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/slideflow_try.py:4) P.extract_tiles(tile_px=256, 
      [5](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/slideflow_try.py:5)                 tile_um=128,
      [6](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/slideflow_try.py:6)                 whitespace_fraction=0.5  # discard tiles with this fraction of whitespace
      [7](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/slideflow_try.py:7)                 )

File ~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1577, in Project.extract_tiles(self, tile_px, tile_um, filters, filter_blank, **kwargs)
   [1454](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1454) """Extract tiles from slides.
   [1455](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1455) 
   [1456](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1456) Preferred use is calling :meth:`slideflow.Dataset.extract_tiles`.
   (...)
   [1568](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1568) 
   [1569](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1569) """
   [1570](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1570) dataset = self.dataset(
   [1571](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1571)     tile_px,
   [1572](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1572)     tile_um,
   (...)
   [1575](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1575)     verification='slides'
   [1576](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1576) )
-> [1577](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:1577) return dataset.extract_tiles(**kwargs)

File ~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/dataset.py:1734, in Dataset.extract_tiles(self, save_tiles, save_tfrecords, source, stride_div, enable_downsample, roi_method, roi_filter_method, skip_extracted, tma, randomize_origin, buffer, q_size, qc, report, use_edge_tiles, artifact_labels, mpp_override, **kwargs)
   [1732](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/dataset.py:1732) ptype = 'spawn' if sf.slide_backend() == 'libvips' else 'fork'
   [1733](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/dataset.py:1733) ctx = mp.get_context(ptype)
-> [1734](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/dataset.py:1734) manager = ctx.Manager()
   [1735](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/dataset.py:1735) reports = manager.dict()
   [1736](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/dataset.py:1736) kwargs['report'] = report

File ~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/context.py:57, in BaseContext.Manager(self)
     [55](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/context.py:55) from .managers import SyncManager
     [56](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/context.py:56) m = SyncManager(ctx=self.get_context())
---> [57](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/context.py:57) m.start()
     [58](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/context.py:58) return m

File ~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/managers.py:558, in BaseManager.start(self, initializer, initargs)
    [556](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/managers.py:556) # get address of server
    [557](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/managers.py:557) writer.close()
--> [558](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/managers.py:558) self._address = reader.recv()
    [559](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/managers.py:559) reader.close()
    [561](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/managers.py:561) # register a finalizer

File ~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:250, in _ConnectionBase.recv(self)
    [248](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:248) self._check_closed()
    [249](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:249) self._check_readable()
--> [250](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:250) buf = self._recv_bytes()
    [251](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:251) return _ForkingPickler.loads(buf.getbuffer())

File ~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:414, in Connection._recv_bytes(self, maxsize)
    [413](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:413) def _recv_bytes(self, maxsize=None):
--> [414](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:414)     buf = self._recv(4)
    [415](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:415)     size, = struct.unpack("!i", buf.getvalue())
    [416](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:416)     if size == -1:

File ~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:383, in Connection._recv(self, size, read)
    [381](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:381) if n == 0:
    [382](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:382)     if remaining == size:
--> [383](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:383)         raise EOFError
    [384](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:384)     else:
    [385](https://file+.vscode-resource.vscode-cdn.net/Users/lmh/Library/CloudStorage/OneDrive-WashingtonUniversityinSt.Louis/HKU/tool_test/SlideFlow/~/miniconda3/envs/slideflow/lib/python3.9/multiprocessing/connection.py:385)         raise OSError("got end of file during message")

EOFError:
```

## Expected behavior

I expect the generation of tiled jpg/png and tfrecords in `tile` folder. And then, I plan to truncate the blank region in slideflow-studio, following by annotating specific tissue ROIs.

## Environment:

 - Slideflow Version (e.g., 1.0): 3.0.2
 - OS (e.g., Ubuntu): M1 MBP, MacOS 12.6.1
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.9.20
 - CUDA/cuDNN version: NA
 - GPU models and configuration: (M1 GPU)
 - Any other relevant information: In conda environment

## Additional context

I have also tried to tile the slides from `dataset` object, but there would also be same error.
```
dataset_all = P.dataset(tile_px=1000, tile_um=250)
dataset_all.extract_tiles()
```

Could you please help me to check how can I keep going? 

Thanks!
Muheng

**Comment by Liao-MH** [comment]
Got it. Finished by arguments: `extract_tiles(..., mpp_override)`

**Comment by maiskovich** [comment]
@Liao-MH I am getting the same error. Could you please explain what argument did you pass to extract_tiles? what is the value of mpp_override?



Thank you
